### ISSUE TITLE
project name?

### ISSUE THREAD

**Issue by edsu** [umd-mith/csvwww#3]
Unfortunately there is a previous project named csvhub:

    https://github.com/theodi/csvhub

Anyone have ideas for another name?

**Comment by edsu** [comment]
I'm thinking csvwww unless someone has a better name :-)

**Comment by raffazizzi** [comment]
sharecvs?

**Comment by edsu** [comment]
csvshare might work too - thanks @raffazizzi

**Comment by edsu** [comment]
ended up going with csvwww because I wanted to recall the webbiness of the idea.
